### ISSUE TITLE
"ghc --make Main.hs" encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [sdiehl/hakyll-bootstrap#1]
hi.

root@AR:/usr/local/hakyll-bootstrap-site# ghc --make Main.hs
[1 of 1] Compiling Main             ( Main.hs, Main.o )

Main.hs:32:36: error:
    • Couldn't match type ‘unordered-containers-0.2.7.2:Data.HashMap.Base.HashMap
                             Data.Text.Internal.Text
                             aeson-1.1.0.0:Data.Aeson.Types.Internal.Value’
                     with ‘M.Map [Char] a0’
      Expected type: M.Map [Char] a0
        Actual type: Metadata
    • In the second argument of ‘M.member’, namely ‘metadata’
      In the expression: "mathjax" `M.member` metadata
      In the second argument of ‘($)’, namely
        ‘if "mathjax" `M.member` metadata then
             "<script type=\"text/javascript\" src=\"http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML\"></script>"
         else
             ""’
root@AR:/usr/local/hakyll-bootstrap-site#

tks

**Comment by sdiehl** [comment]
Use the project's cabal file and either Stack or Sandboxes to build it. Otherwise it's just not using the right versions of the libraries.

**Comment by sdiehl** [comment]
Should be fixed by using the new stack instructions.
