### ISSUE TITLE
Update to recent version of 'hakyl' and GHC

### ISSUE THREAD

**Issue by chshersh** [sdiehl/hakyll-bootstrap#2]
This repository it very old... But it is the only simple example that has Hakyll with Bootstrap. Also, the first googlable... I will really appreciate updating this repo!

**Comment by sdiehl** [comment]
Using Stack it would probably take like an hour to update it to modern Hakyll

**Comment by chshersh** [comment]
@sdiehl I can try to update it later via Pull Request. Currently I'm working on website with Hakyll + Bootstrap. So this shouldn't be so hard to do...

**Comment by sdiehl** [comment]
@ChShersh This should be updated for modern GHC and Haskell. Let me know if this fixes your problem.
